name: Pylint

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: auto-osint-v-python38
        environment-file: environment.yml
        auto-activate-base: false
    - name: Install dependencies
      run: |
        conda install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under 8 $(git ls-files '*.py')
